#!/usr/bin/env python
import sys
import os

from recon.trans import dsres2meld

if len(sys.argv)!=2:
   print "Usage: "+str(sys.argv[0])+" <mat-file>"
   sys.exit(1)

name, ext = os.path.splitext(sys.argv[1])

with open(sys.argv[1], "rb") as wfp:
     with open(name+".mld", "w+") as mfp:
     	  dsres2meld(wfp, mfp)
