#!/usr/bin/env python
import sys
import os

from recon.trans import dsres2meld

if len(sys.argv)!=2:
   print "Usage: "+str(sys.argv[0])+" <mat-file>"
   sys.exit(1)

name, ext = os.path.splitext(sys.argv[1])

wfile = sys.argv[1]
mfile = name+".mld"

dsres2meld(wfile, mfile)
